apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"default","name":"wldandan","uid":"02d4c451-4ddc-11e9-8ec4-0800272dd534","apiVersion":"v1","resourceVersion":"253232"}}
  creationTimestamp: 2019-03-24T02:24:54Z
  generateName: wldandan-
  labels:
    run: wldandan
  name: wldandan-rshvl
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: wldandan
    uid: 02d4c451-4ddc-11e9-8ec4-0800272dd534
  resourceVersion: "260449"
  selfLink: /api/v1/namespaces/default/pods/wldandan-rshvl
  uid: 02d5dd35-4ddc-11e9-8ec4-0800272dd534
spec:
  containers:
  - image: wldandan/latest
    imagePullPolicy: Always
    name: wldandan
    ports:
    - containerPort: 8081
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rv2k0
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-rv2k0
    secret:
      defaultMode: 420
      secretName: default-token-rv2k0
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-03-24T02:24:54Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-03-24T02:24:54Z
    message: 'containers with unready status: [wldandan]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-03-24T02:24:54Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: wldandan/latest
    imageID: ""
    lastState: {}
    name: wldandan
    ready: false
    restartCount: 0
    state:
      waiting:
        message: Back-off pulling image "wldandan/latest"
        reason: ImagePullBackOff
  hostIP: 192.168.99.100
  phase: Pending
  podIP: 172.17.0.6
  qosClass: BestEffort
  startTime: 2019-03-24T02:24:54Z
